name: Cypress training CI

on: push

jobs:
  chrome-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: "LackeyLiesmith/test-cypress-ci"
          path: "test-cypress-ci"
      - name: Run Docker Compose
        run: |
          cd test-cypress-ci
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh
      - run: npm install
      - uses: browser-actions/setup-chrome@v1
      - name: Run Cypress tests
        run: npx cypress run --browser chrome

  firefox-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: "LackeyLiesmith/test-cypress-ci"
          path: "test-cypress-ci"
      - name: Run Docker Compose
        run: |
          cd test-cypress-ci
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh
      - run: npm install
      - uses: browser-actions/setup-firefox@v1
      - name: Run Cypress tests
        run: npx cypress run --browser firefox
